from django.contrib import sitemaps
from django.contrib.sitemaps import Sitemap
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

class SiteMap(sitemaps.Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        return [
            'home',
            'about',
            'disclaimer',
            'contact',

            'hillsborough-dui',
            'hillsborough-battery',
            'hillsborough-marijuanaposs',
            'hillsborough-petit-theft',
            'hillsborough-dwlsr',
            'hills-dui-farr',
            'hills-dui-greco',
            'hills-dui-jeske',
            'hills-dui-lefler',
            'hills-dui-mcneil',
            'hills-dui-myers',
            'hills-dui-taylor',
            'hills-dui-dui',
            'hills-battery-farr',
            'hills-battery-greco',
            'hills-battery-jeske',
            'hills-battery-lefler',
            'hills-battery-mcneil',
            'hills-battery-myers',
            'hills-battery-taylor',
            'hills-battery-battery',
            'hills-dwlsr-farr',
            'hills-dwlsr-greco',
            'hills-dwlsr-jeske',
            'hills-dwlsr-lefler',
            'hills-dwlsr-mcneil',
            'hills-dwlsr-myers',
            'hills-dwlsr-taylor',
            'hills-dwlsr-dwlsr',
            'hills-marijuana-possession-farr',
            'hills-marijuana-possession-greco',
            'hills-marijuana-possession-jeske',
            'hills-marijuana-possession-lefler',
            'hills-marijuana-possession-mcneil',
            'hills-marijuana-possession-myers',
            'hills-marijuana-possession-taylor',
            'hills-marijuana-possession-marijuana-possession',
            'hills-petit-theft-farr',
            'hills-petit-theft-greco',
            'hills-petit-theft-jeske',
            'hills-petit-theft-lefler',
            'hills-petit-theft-mcneil',
            'hills-petit-theft-myers',
            'hills-petit-theft-taylor',
            'hills-petit-theft-petit-theft',

            'pinellas-dui',
            'pinellas-marijuana-possession',
            'pinellas-battery',
            'pinellas-dwlsr',
            'pinellas-petit-theft',
            'pinellas-dwlsr-bedinghaus',
            'pinellas-dwlsr-carballo',
            'pinellas-dwlsr-dittmer',
            'pinellas-dwlsr-horrox',
            'pinellas-dwlsr-levine',
            'pinellas-dwlsr-mckyton',
            'pinellas-dwlsr-overton',
            'pinellas-dwlsr-pierce',
            'pinellas-dwlsr-dwlsr',
            'pinellas-battery-bedinghaus',
            'pinellas-battery-carballo',
            'pinellas-battery-dittmer',
            'pinellas-battery-horrox',
            'pinellas-battery-levine',
            'pinellas-battery-mckyton',
            'pinellas-battery-overton',
            'pinellas-battery-pierce',
            'pinellas-battery-battery',
            'pinellas-dui-bedinghaus',
            'pinellas-dui-carballo',
            'pinellas-dui-dittmer',
            'pinellas-dui-horrox',
            'pinellas-dui-levine',
            'pinellas-dui-mckyton',
            'pinellas-dui-overton',
            'pinellas-dui-pierce',
            'pinellas-dui-dui',
            'pinellas-marijuana-possession-bedinghaus',
            'pinellas-marijuana-possession-carballo',
            'pinellas-marijuana-possession-dittmer',
            'pinellas-marijuana-possession-horrox',
            'pinellas-marijuana-possession-levine',
            'pinellas-marijuana-possession-mckyton',
            'pinellas-marijuana-possession-overton',
            'pinellas-marijuana-possession-pierce',
            'pinellas-marijuana-possession-marijuana-possession',
            'pinellas-petit-theft-bedinghaus',
            'pinellas-petit-theft-carballo',
            'pinellas-petit-theft-dittmer',
            'pinellas-petit-theft-horrox',
            'pinellas-petit-theft-levine',
            'pinellas-petit-theft-mckyton',
            'pinellas-petit-theft-overton',
            'pinellas-petit-theft-pierce',
            'pinellas-petit-theft-petit-theft',
            ]


    def location(self, item):
        return reverse(item)
